WebProgramlamaMatematikciyiz/Controllers/DerslersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProgramlamaMatematikciyiz.Models;

namespace WebProgramlamaMatematikciyiz.Controllers
{
    public class DerslersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Derslers
        public async Task<ActionResult> Index()
        {
            return View(await db.Derslers.ToListAsync());
        }
        [Authorize(Roles = "Admin")]
        // GET: Derslers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dersler dersler = await db.Derslers.FindAsync(id);
            if (dersler == null)
            {
                return HttpNotFound();
            }
            return View(dersler);
        }
        [Authorize(Roles ="Admin")]
        // GET: Derslers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Derslers/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "DersID,DersAdi")] Dersler dersler)
        {
            if (ModelState.IsValid)
            {
                db.Derslers.Add(dersler);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(dersler);
        }
        [Authorize(Roles = "Admin")]
        // GET: Derslers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dersler dersler = await db.Derslers.FindAsync(id);
            if (dersler == null)
            {
                return HttpNotFound();
            }
            return View(dersler);
        }

        // POST: Derslers/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "DersID,DersAdi")] Dersler dersler)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dersler).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(dersler);
        }

        // GET: Derslers/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dersler dersler = await db.Derslers.FindAsync(id);
            if (dersler == null)
            {
                return HttpNotFound();
            }
            return View(dersler);
        }

        // POST: Derslers/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Dersler dersler = await db.Derslers.FindAsync(id);
            db.Derslers.Remove(dersler);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebProgramlamaMatematikciyiz/Controllers/KonuVideosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProgramlamaMatematikciyiz.Models;

namespace WebProgramlamaMatematikciyiz.Controllers
{
    public class KonuVideosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [Authorize]
        // GET: KonuVideos
        public async Task<ActionResult> Index()
        {
            var konuAnlatimVideos = db.KonuAnlatimVideos.Include(k => k.Konulars);
            return View(await konuAnlatimVideos.ToListAsync());
        }

        // GET: KonuVideos/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KonuVideo konuAnlatimVideo = await db.KonuAnlatimVideos.FindAsync(id);
            db.KonuAnlatimVideos.Include(x => x.Konulars).Include(x => x.Konulars.Dersler).ToList();
            ViewBag.link = konuAnlatimVideo.Link;

            if (konuAnlatimVideo == null)
            {
                return HttpNotFound();
            }
            return View(konuAnlatimVideo);
        }

        // GET: KonuVideos/Create
        public ActionResult Create()
        {
            ViewBag.KonuID = new SelectList(db.KonuAnlatims, "KonuID", "KonuAdi");
            return View();
        }

        // POST: KonuVideos/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "KonuVideoID,Link,KonuID")] KonuVideo konuVideo)
        {
            if (ModelState.IsValid)
            {
                db.KonuAnlatimVideos.Add(konuVideo);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.KonuID = new SelectList(db.KonuAnlatims, "KonuID", "KonuAdi", konuVideo.KonuID);
            return View(konuVideo);
        }

        // GET: KonuVideos/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KonuVideo konuVideo = await db.KonuAnlatimVideos.FindAsync(id);
            if (konuVideo == null)
            {
                return HttpNotFound();
            }
            ViewBag.KonuID = new SelectList(db.KonuAnlatims, "KonuID", "KonuAdi", konuVideo.KonuID);
            return View(konuVideo);
        }

        // POST: KonuVideos/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "KonuVideoID,Link,KonuID")] KonuVideo konuVideo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(konuVideo).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.KonuID = new SelectList(db.KonuAnlatims, "KonuID", "KonuAdi", konuVideo.KonuID);
            return View(konuVideo);
        }

        // GET: KonuVideos/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KonuVideo konuVideo = await db.KonuAnlatimVideos.FindAsync(id);
            if (konuVideo == null)
            {
                return HttpNotFound();
            }
            return View(konuVideo);
        }

        // POST: KonuVideos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            KonuVideo konuVideo = await db.KonuAnlatimVideos.FindAsync(id);
            db.KonuAnlatimVideos.Remove(konuVideo);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebProgramlamaMatematikciyiz/Views/Shared/_Layout.cshtml
@using WebProgramlamaMatematikciyiz.App_GlobalResources;
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Matematikciyiz</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Matematikciyiz", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(turkce_language.Anasayfa, "Index", "Home")</li>
                    <li>@Html.ActionLink(turkce_language.Konuanlatimvideoları ,"Index", "KonuVideos")</li>
                    <li>@Html.ActionLink(turkce_language.Dersler, "Index", "Derslers")</li>
                    <li>@Html.ActionLink(turkce_language.Hakkımızda, "About", "Home")</li>
                    <li>@Html.ActionLink(turkce_language.İletişim, "Contact", "Home")</li>

                    <li>@Html.ActionLink(turkce_language.Türkçe, "ChangeLanguage", "Home", new { lang = "Tr" }, null)</li>
                    <li>@Html.ActionLink(turkce_language.İngilizce, "ChangeLanguage", "Home", new { lang = "En" },null )</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Matematikciyiz.com</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>